### ISSUE TITLE
Can't change colour of crosstab

### ISSUE THREAD

**Issue by cwthom** [datasciencecampus/synthgauge#1]
Hi there, 

I recently used synthgauge as part of a gov hackathon, and thought it was fantastic - really useful package! Came across one small bug, where I couldn't change the colour of a crosstab plot, because the colorbar didn't reflect the update. I was passing in eg. `cmap='Blues'` to the `plot_crosstab` method, and as per the docs it passed through to `sns.heatmap`, but not to the colorbar alongside the plot. I think the key lines are these, where the `fig.colorbar` call can't be modified:

https://github.com/datasciencecampus/synthgauge/blob/28badf14f8537cab7f3c9fb7c83dd8039d4dc06b/src/synthgauge/plot.py#L445-L455

Simplest solution would probably be to just have `cmap` exposed as an argument with a default setting, but I guess you could also check if `cmap` is passed as part of `kwargs` and add it into the `fig.colorbar` call if so?

Thanks again for the great package!

**Comment by owendanielONS** [comment]
@cwthom - Many thanks for flagging this, and for the kind words about the package. We'll take a look.
