### ISSUE TITLE
Not available on PyPI?

### ISSUE THREAD

**Issue by abdrysdale** [datasciencecampus/synthgauge#2]
Thanks for the fantastic repo - it looks great!

I was just wondering why this isn't available on the Python package index? I think that would be a useful feature so I just wanted to check if there are any plans for this and if not, if I'm okay to fork the repository and publish on PyPI - from the license it seems so but I wanted to double check if first.

Again, thanks for a great repository for such a crucial area.

**Comment by daffidwilde** [comment]
Hi @abdrysdale!

Thanks for raising this and you're definitely right. We've reviewed this with our internal team and should be able to publish this package to PyPI, so please do hold off on publishing it yourself! 😄

**Comment by daffidwilde** [comment]
Just logging an update on this @abdrysdale

We put off publishing to PyPI while we did some core development work on the package. Thankfully, that's all ready to go now, so expect version `1.0.0` (and the latest `2.0.0`) at some point next week.

Have a good weekend! ✨

**Comment by daffidwilde** [comment]
Good morning @abdrysdale - I'm happy to say `synthgauge` is now pip-installable: https://pypi.org/project/synthgauge/

Thanks again for raising this issue and for using the package.

**Comment by abdrysdale** [comment]
Thanks very much - really appreciate it!
